# Site settings
title: Cooing Tech Blog
email: certekim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CooingTech aka Cool In Technologies
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cooing.tech" # the base hostname & protocol for your site
twitter_username: certekim
github_username:  CerteKim
facebook_username: 
google_play: 
google_plus_com:   # Community link
google_plus_per:   #Personal link
facebook_app_id: 

# Layout settings
header_type: drawer # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: GitHub
    link: gihub.com/CerteKim
  option2:
    name: Certe.Kim
    link: certe.kim
  option3:
    name: EndlessDream.Games
    link: endlessdream.games

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
